from enum import StrEnum

COOKIE_NAME = 'access_token'
JWT_ALGORITHM = 'HS256'
JWT_EXPIRE_DAYS = 30


class ErrorCode(StrEnum):
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
    INVALID_TOKEN = 'INVALID_TOKEN'  # noqa: S105
    NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
