from enum import StrEnum

COOKIE_NAME = 'access_token'
JWT_ALGORITHM = 'HS256'
JWT_EXPIRE_DAYS = 30
MAGIC_LINK_EXPIRE_MINUTES = 15


class ErrorCode(StrEnum):
    INVALID_TOKEN = 'INVALID_TOKEN'  # noqa: S105
    TOKEN_EXPIRED = 'TOKEN_EXPIRED'  # noqa: S105
    EMAIL_NOT_ALLOWED = 'EMAIL_NOT_ALLOWED'
    NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
